In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [3]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [4]:
x1 = np.array([5, 15, 25, 35, 45, 55])

In [5]:
x1.shape

(6,)

In [6]:
y

array([ 5, 20, 14, 32, 22, 38])

In [7]:
x.shape

(6, 1)

In [8]:
model = LinearRegression()

In [9]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
r_sq = model.score(x, y)

In [13]:
print('coefficient of determination : ', r_sq)

coefficient of determination :  0.7158756137479542


In [14]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [15]:
print('slope:', model.coef_)

slope: [0.54]


In [16]:
y_pred = model.predict(x)

In [17]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [18]:
y_pred = model.intercept_ + model.coef_ * x

In [21]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [24]:
from sklearn.metrics import mean_squared_error, r2_score

In [25]:
mean_squared_error(y, y_pred)

33.75555555555555